### ISSUE TITLE
Review and revise wire harness drawings

### ISSUE THREAD

**Issue by FlyingBowser** [Ohm-Slah/Gallagher-Station-Duke-Energy-Museum-Exhibit#63]
All wire harness drawings are in the docs -> dwg -> CABLE AND WIRE HARNESS CONNECTORS. These files need to be revised and updated

**Comment by Ohm-Slah** [comment]
@Jack12COuch8 What is your progress on this?

**Comment by FlyingBowser** [comment]
Connectors have been revised and edited for current PCB schematics. Closed Issue
