### ISSUE TITLE
Add 1320 DWG

### ISSUE THREAD

**Issue by Ohm-Slah** [Ohm-Slah/Gallagher-Station-Duke-Energy-Museum-Exhibit#68]
Cable diagram for the 1300 dwg's are missing.
@Jack12COuch8 @FlyingBowser 
Is this file not necessary? I'm pretty sure there's a cable going from Arduino board to 7-segment board, 4-wires on 5-pin connectors.

**Comment by FlyingBowser** [comment]
That is correct there is a single cable, but it is a board- board cable and is referenced on drawing 112x. BOM on 1300 references correct drawing. 1320 is not necessary
